import React, { useContext } from "react";
import GlobalContext from "@/complements/components/GlobalContextComp/GlobalContextComp";
import Image from "next/image";
import Head from "next/head";
import HeaderComp from "@/complements/components/HeaderComp/HeaderComp";
import PagesHeadComp from "@/complements/components/PagesHeadComp/PagesHeadComp";
import FooterComp from "@/complements/components/FooterComp/FooterComp";
import styles from '@/styles/aboutUs.module.css'

export default function AboutUs(){
  //------ User global context ------
  const { Environment,UsrCookie,setUsrCookie}: any = useContext(GlobalContext)

  const GetInTouch = (e:any) =>{

  }

    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
            </Head>
            <PagesHeadComp
                data={{
                    faviconURL: "/Icons/manifest_icons/appyyo.png", //URL of icon to be displayed besides the title tab.
                    title: "Appy.yo® - Home", //Title to be displayed in the tab. In case of traslations needs to consider the marker and tag to be traslated, such as this sample.
                    description: "", //Description to be read by SEO for this page
                    keywords: "", //Keywords to be read by SEO for this page
                }}
            />
            <HeaderComp 
                logo={'/Icons/manifest_icons/MaskableLogo.png'}
                menus={[
                    {
                        menu: 'Home',
                        link: '/'
                    },
                    {
                        menu: 'About Us',
                        link: '/AboutUs'
                    },
                    {
                        menu: 'Innovation Lab',
                        link: '/InnovationLab'
                    },
                    {
                        menu: 'Newest Project',
                        link: '/NewestProject'
                    },
                    {
                        menu: 'Professional Services',
                        link: '/ProfessionalServices'
                    },
                    {
                        menu: 'Digital Transformation',
                        link: '/DigitalTransformation'
                    },
                ]}
                signin='Get in Touch'
                onClick={(e:any)=>GetInTouch(e)}
            />

            <main className={styles.main}>
                <div className={styles.Image}>
                    <Image className={styles.Img} src="/Images/AppyyoLogo.jpg" fill alt="Digital_Transformation"/>
                </div>
                <article className={styles.article}>
                    <h1>About Us</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut porro necessitatibus, officia perspiciatis, labore tempora, facere itaque beatae ullam tempore quidem maiores excepturi dolor rem officiis illo. Saepe, est. Quod.</p><br/>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut porro necessitatibus, officia perspiciatis, labore tempora, facere itaque beatae ullam tempore quidem maiores excepturi dolor rem officiis illo. Saepe, est. Quod.</p><br/>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut porro necessitatibus, officia perspiciatis, labore tempora, facere itaque beatae ullam tempore quidem maiores excepturi dolor rem officiis illo. Saepe, est. Quod.</p><br/>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut porro necessitatibus, officia perspiciatis, labore tempora, facere itaque beatae ullam tempore quidem maiores excepturi dolor rem officiis illo. Saepe, est. Quod.</p><br/>
                </article>
                <div className={styles.bubbles}>
                    <div className={styles.bubble}>
                        <h2>Topic</h2>
                        <span className={styles.BubImg}>
                            <Image className={styles.BImg} src="/Images/DigitalTransformation.jpeg" fill alt="Digital_Transformation"/>
                        </span>
                    </div>
                    <div className={styles.bubble}>
                        <h2>Topic</h2>
                        <span className={styles.BubImg}>
                            <Image className={styles.BImg} src="/Images/InnovationLab.jpeg" fill alt="Digital_Transformation"/>
                        </span>
                    </div>
                    <div className={styles.bubble}>
                        <h2>Topic</h2>
                        <span className={styles.BubImg}>
                            <Image className={styles.BImg} src="/Images/ProfesionalServices.jpeg" fill alt="Digital_Transformation"/>
                        </span>
                    </div>
                    <div className={styles.bubble}>
                        <h2>Topic</h2>
                        <span className={styles.BubImg}>
                            <Image className={styles.BImg} src="/Images/EmailMarketing.jpeg" fill alt="Digital_Transformation"/>
                        </span>
                    </div>
                    <div className={styles.bubble}>
                        <h2>Topic</h2>
                        <span className={styles.BubImg}>
                            <Image className={styles.BImg} src="/Images/project.jpeg" fill alt="Digital_Transformation"/>
                        </span>
                    </div>
                    <div className={styles.bubble}>
                        <h2>Topic</h2>
                        <span className={styles.BubImg}>
                            <Image className={styles.BImg} src="/Images/Icons.jpeg" fill alt="Digital_Transformation"/>
                        </span>
                    </div>
                </div>
            </main>

            <FooterComp 
                copyright= {'Appy.yo'}
                classNames={''}
                langs={{
                developed: "Developed by",
                copyright: "Copyright",
                made: "made",
                version: "version",
                }}
            />
        </>
    )
}