import React from "react";
import Head from "next/head";
import HeaderComp from "@/complements/components/HeaderComp/HeaderComp";
import PagesHeadComp from "@/complements/components/PagesHeadComp/PagesHeadComp";
import FooterComp from "@/complements/components/FooterComp/FooterComp";
import styles from '@/styles/GetInTouch.module.css'

export default function GetinTouch(){
    return (
        <>
            <Head>
                <title>Get in Touch</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
                <meta name="theme-color" content="#2F303A" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta httpEquiv='ScreenOrientation' content='autoRotate:disabled' />
            </Head>
            <PagesHeadComp
                data={{
                    faviconURL: "/Icons/manifest_icons/appyyo.png", //URL of icon to be displayed besides the title tab.
                    title: "Appy.yo® - Home", //Title to be displayed in the tab. In case of traslations needs to consider the marker and tag to be traslated, such as this sample.
                    description: "", //Description to be read by SEO for this page
                    keywords: "", //Keywords to be read by SEO for this page
                }}
            />
            <HeaderComp 
                logo={'/Icons/manifest_icons/MaskableLogo.png'}
                menus={[
                    {
                        menu: 'Home',
                        link: '/'
                    },
                    {
                        menu: 'About Us',
                        link: '/AboutUs'
                    },
                    {
                        menu: 'Innovation Lab',
                        link: '/InnovationLab'
                    },
                    {
                        menu: 'Newest Project',
                        link: '/NewestProject'
                    },
                    {
                        menu: 'Professional Services',
                        link: '/ProfessionalServices'
                    },
                    {
                        menu: 'Digital Transformation',
                        link: '/DigitalTransformation'
                    },
                    {
                        menu: 'Get in Touch',
                        link: '/GetInTouch'
                    },
                ]}
            />
            <main>
                <div className={styles.container}>
                    <form action="#" method="post">
                        <label htmlFor="name">Name:*</label>
                        <input autoFocus type="text" placeholder="Please enter your First Name " id="name" name="name" required />
                        <label htmlFor="address">Address</label>
                        <textarea id="address" name="address"></textarea>
                        <label htmlFor="email">Email Address:*</label>
                        <input type="email" placeholder="Please enter your Email " id="email" name="email" required />
                        <label htmlFor="phone">Phone *</label>
                        <input type="tel" id="phone" name="phone" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" required/>
                        <label htmlFor="subject">Subject:</label>
                        <input type="text" id="subject" name="subject" />
                        <label htmlFor="msg">Message:</label>
                        <textarea id="msg" name="msg" rows={5} placeholder="Type your Message Here..."></textarea>
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </main>
            <FooterComp 
                classNames={''}
                langs={{
                developed: "Developed by",
                copyright: "Copyright",
                made: "made",
                version: "version",
                }}
            />
        </>
    )
}