import Head from 'next/head'
import Link from 'next/link';
import React from 'react';
import styles from '@/styles/Home.module.css'
import PagesHeadComp from '@/complements/components/PagesHeadComp/PagesHeadComp'
import HeaderComp from '@/complements/components/HeaderComp/HeaderComp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Appy.yo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#2F303A" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv='ScreenOrientation' content='autoRotate:disabled' />
        <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
      </Head>
      <PagesHeadComp
        data={{
            faviconURL: "/Icons/manifest_icons/appyyo.png",
            title: "Appy.yo® - Home",
            description: "",
            keywords: "",
        }}
      />
      <main className={styles.main}>
        <div className={styles.GetTouchCont}>
          <a href={'/GetInTouch'} className={styles.MenuButton}>Get In Touch</a>
        </div>
        <div id={styles.MainLinksMenu}>
          <Link id={styles.NewestProject} className={styles.MainLink} href="/NewestProject"><span>Projects</span></Link>
          <Link id={styles.InnovationLab} className={styles.MainLink} href="/InnovationLab"><span>Innovation Lab</span></Link>
          <Link id={styles.ProfessionalServices} className={styles.MainLink} href="/ProfessionalServices"><span>Professional Services</span></Link>
          <Link id={styles.AboutUs} className={styles.MainLink} href="/AboutUs"><span>About Us</span></Link>
          <Link id={styles.DigitalTransformation} className={styles.MainLink} href="/DigitalTransformation"><span>Digital Transformation</span></Link>
        </div>
      </main>
    </>
  )
}
