import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image';
import React, {  useContext } from 'react';
import styles from '@/styles/Home.module.css'
import PagesHeadComp from '@/complements/components/PagesHeadComp/PagesHeadComp'
import GlobalContext from '@/complements/components/GlobalContextComp/GlobalContextComp'
import HeaderComp from '@/complements/components/HeaderComp/HeaderComp'
import FooterComp from '@/complements/components/FooterComp/FooterComp'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //------ User global context ------
  const { Environment,UsrCookie,setUsrCookie}: any = useContext(GlobalContext)

  function HandleSignIn(e:any){
    console.log(e)
  }

  return (
    <>
      <Head>
        <title>Appy.yo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
      </Head>
      <PagesHeadComp
        data={{
            faviconURL: "/Icons/manifest_icons/appyyo.png",
            title: "Appy.yo® - Home",
            description: "",
            keywords: "",
        }}
      />
      <main className={styles.main}>
        <HeaderComp 
          signin='Get in Touch'
          onClick={(e:any)=>HandleSignIn(e)}
        />
        <div id={styles.MainLinksMenu}>
          <Link id={styles.NewestProject} className={styles.MainLink} href="/NewestProject"><span>Newest Project</span></Link>
          <Link id={styles.InnovationLab} className={styles.MainLink} href="/InnovationLab"><span>Innovation Lab</span></Link>
          <Link id={styles.ProfessionalServices} className={styles.MainLink} href="/ProfessionalServices"><span>Professional Services</span></Link>
          <Link id={styles.AboutUs} className={styles.MainLink} href="/AboutUs"><span>About Us</span></Link>
          <Link id={styles.DigitalTransformation} className={styles.MainLink} href="/DigitalTransformation"><span>Digital Transformation</span></Link>
        </div>
      </main>
        {/*Footer Component*/}
        <FooterComp 
            classNames={''}
            langs={{
              developed: "Developed by",
              copyright: "Copyright",
              made: "made",
              version: "version",
            }}
        />
    </>
  )
}
