import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image';
import React from 'react';
import styles from '@/styles/Home.module.css'
import PagesHeadComp from '@/complements/components/PagesHeadComp/PagesHeadComp'
import HeaderComp from '@/complements/components/HeaderComp/HeaderComp'
import FooterComp from '@/complements/components/FooterComp/FooterComp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Appy.yo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#2F303A" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv='ScreenOrientation' content='autoRotate:disabled' />
        <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
      </Head>
      <PagesHeadComp
        data={{
            faviconURL: "/Icons/manifest_icons/appyyo.png",
            title: "Appy.yo® - Home",
            description: "",
            keywords: "",
        }}
      />
      <main className={styles.main}>
        <HeaderComp 
                menus={[
                  {
                      menu: 'Get in Touch',
                      link: '/GetInTouch'
                  },
              ]}
        />
        <div id={styles.MainLinksMenu}>
          <div id={styles.AbUsMainLink}>
            <Image id={styles.AbUsImg} src={'/Images/AppyyoCrop.png'} fill alt=""/>
          </div>
          <Link id={styles.NewestProject} className={styles.MainLink} href="/NewestProject"><span>Newest Project</span></Link>
          <Link id={styles.InnovationLab} className={styles.MainLink} href="/InnovationLab"><span>Innovation Lab</span></Link>
          <Link id={styles.ProfessionalServices} className={styles.MainLink} href="/ProfessionalServices"><span>Professional Services</span></Link>
          <Link id={styles.AboutUs} className={styles.MainLink} href="/AboutUs"><span>About Us</span></Link>
          <Link id={styles.DigitalTransformation} className={styles.MainLink} href="/DigitalTransformation"><span>Digital Transformation</span></Link>
        </div>
      </main>
        {/*Footer Component*/}
        <FooterComp 
            classNames={''}
            langs={{
              developed: "Developed by",
              copyright: "Copyright",
              made: "made",
              version: "version",
            }}
        />
    </>
  )
}
